Update build_publish.yml

diff --git a/.github/workflows/build_publish.yml b/.github/workflows/build_publish.yml
--- a/.github/workflows/build_publish.yml
+++ b/.github/workflows/build_publish.yml
@@ -46,4 +46,23 @@ jobs:
           file: package/docker/Dockerfile
           push: true
           tags: bahmni/odoo-connect:${{env.ARTIFACT_VERSION}},bahmni/odoo-connect:latest
-          
+  trigger-workflow:
+    name: Trigger workflow to deploy to docker env
+    needs: 
+      - docker-build-publish
+    runs-on: ubuntu-latest
+    env:
+      ORG_NAME: Bahmni
+      REPOSITORY_NAME: bahmni-docker
+      EVENT_TYPE: odoo-connect-publish-event
+    steps:
+      - name: Create repository_dispatch
+        run: |
+          trigger_result=$(curl -s -o trigger_response.txt -w "%{http_code}" -X POST -H "Accept: application/vnd.github.v3+json" -H 'authorization: Bearer ${{ secrets.BAHMNI_PAT }}' https://api.github.com/repos/${ORG_NAME}/${REPOSITORY_NAME}/dispatches -d '{"event_type":"'"${EVENT_TYPE}"'"}')
+          if [ $trigger_result == 204 ];then
+            echo "Trigger to $ORG_NAME/$REPOSITORY_NAME Success"
+          else
+            echo "Trigger to $ORG_NAME/$REPOSITORY_NAME Failed"
+            cat trigger_response.txt
+            exit 1
+          fi
